#!/bin/sh
set -e

. tools/check

[ -f punch ] || tools/build
[ -d "$1$db_dir/$name" ] || install -dm700 "$1$db_dir/$name"
install -Dm4755 punch "$1$prefix$bin_dir/$name"
install -Dm644 punch.1 "$1$prefix$man_dir/man1/$name.1"
